var compo = compo || {}
compo = {
	main_navi : ()=>{
		return '<div id="header">'
		+'	<div class="wrap">'
		+'			<h1 class="logo fl">'
						+'<a><img id="logo" alt="여행의 시작! 어스토리" ></a>'
		+'			</h1>'
		+'			<ul class="gnb fl">'
		+'				<a href="/ko/area" class="fl"><li class="on">여행지</li></a>'
		+'				<a href="/ko/plan" class="fl"><li>일정만들기</li></a>'
						+'<a href="https://www.agoda.com/?cid=1607809" class="fl" target="_blank"><li>호텔</li></a>'
		+'				<a href="/ko/intro" class="fl"><li>이용방법</li></a>'
		+'			</ul>'
		+'		<div class="fr gnb_box">'
						+"<a href='javascript:void(0)' class='fr' onclick='et_modal('365px','499px','1','0','/ko/member/join','2','1')'><div class='fl gnb_join_btn'>회원가입</div></a>"
						+"<a href='javascript:void(0)' class='fr' onclick='et_modal('365px','380px','1','0'','/ko/member','2','1')'><div class='fl gnb_login_btn'>로그인</div></a>"
		+'				<a href="javascript:void(0);" class="fr" style="display:none;">'
					+'<div class="fl gnb_set_box_currency script-popup" data-scp_child="gnb_set_box_open_currency" data-scp_ani="fade">'
		+'				<div style="padding-left:15px;">KRW</div>'
		+'			</div>'
					+'<div class="fl gnb_set_box_lang script-popup" data-scp_child="gnb_set_box_open_lang" data-scp_ani="fade">'
		+'				<div style="width:81px;padding-left:12px;">한국어</div>'
		+'			</div>			'
		+'					</a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'	<div class="clear"></div>'
		+'	<div id="common_area"></div>'
	},
	tourist_area : ()=>{
		return '<div class="area_top" id="area_top">'
		+'<div class="wrap">'
		+'	<div class="area_top_title">어디로 여행을 가시나요?</div>'
		+'		<div class="search_area">'
		+'			<input class="search_input" id="city_search" placeholder="국가명, 도시명으로 검색">'
		+'			<div id="city_autocomplete"></div>'
		+'			<div class="latest_search">	추천도시 :<a href="/ko/city/singapore_243" class="latest_a">싱가포르</a>'
		+'				,<a href="/ko/city/paris_307" class="latest_a">파리</a>'
		+'				,<a href="/ko/city/jeju_312" class="latest_a">제주도</a>'
		+'		</div>'
		+'			<a class="go_map" href="javascript:void(0)" onclick="et_full_modal("/ko/modal/world_map")">지도에서 검색 ></a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'<div class="area_white">'
		+'	<div class="wrap">'
		+'		<div class="area_title">'
		+'			국가리스트		</div>'
		+'		<div class="area_top_name as">'
		+'			아시아		</div>'
		+'		<div class="area_list as">'
		+'			<a href="/ko/area/nepal" class="area_n_link">'
		+'				마카오&nbsp;<span>Macau</span>'
		+'			</a>'
		+'			<a href="/ko/area/taiwan" class="area_n_link">'
		+'				인도네시아&nbsp;<span>Indonesia</span>'
		+'			</a>'
		+'			<a href="/ko/area/republic-of-korea" class="area_n_link">'
		+'				몰디브&nbsp;<span>Maldives</span>'
		+'			</a>'
		+'			<a href="/ko/area/laos" class="area_n_link">'
		+'				라오스&nbsp;<span>Laos</span>'
		+'			</a>'
		+'			<a href="/ko/area/vietnam" class="area_n_link">'
		+'				베트남&nbsp;<span>Vietnam</span>'
		+'			</a>'
		+'			<a href="/ko/area/sri-lanka" class="area_n_link">'
		+'				스리랑카&nbsp;<span>Sri Lanka</span>'
		+'			</a>'
		+'			<a href="/ko/area/singapore" class="area_n_link">'
		+'				싱가포르&nbsp;<span>Singapore</span>'
		+'			</a>'
		+'			<a href="/ko/area/myanmar" class="area_n_link">'
		+'				미얀마(버마)&nbsp;<span>Myanmar</span>'
		+'			</a>'
		+'			<a href="/ko/area/india" class="area_n_link">'
		+'				인도&nbsp;<span>India</span>'
		+'			</a>'
		+'			<a href="/ko/area/thailand" class="area_n_link">'
		+'				태국&nbsp;<span>Thailand</span>'
		+'			</a>'
		+'			<a href="/ko/area/japan" class="area_n_link">'
		+'				일본&nbsp;<span>Japan</span>'
		+'			</a>'
		+'			<a href="/ko/area/china" class="area_n_link">'
		+'				중국&nbsp;<span>China</span>'
		+'			</a>'
		+'			<a href="/ko/area/philippines" class="area_n_link">'
		+'				필리핀&nbsp;<span>Philippines</span>'
		+'			</a>'
		+'			<a href="/ko/area/hongkong" class="area_n_link">'
		+'				홍콩&nbsp;<span>Hongkong</span>'
		+'			</a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="area_top_name eu">'
		+'			유럽		</div>'
		+'		<div class="area_list eu">'
		+'			<a class="area_n_link" id="germany">'
		+'				독일&nbsp;<span>Germany</span>'
		+'			</a>'
		+'			<a href="/ko/area/united-kingdom" class="area_n_link">'
		+'				영국&nbsp;<span>United Kingdom</span>'
		+'			</a>'
		+'			<a href="/ko/area/russia" class="area_n_link">'
		+'				러시아&nbsp;<span>Russia</span>'
		+'			</a>'
		+'			<a href="/ko/area/poland" class="area_n_link">'
		+'				폴란드&nbsp;<span>Poland</span>'
		+'			</a>'
		+'			<a href="/ko/area/denmark" class="area_n_link">'
		+'				덴마크&nbsp;<span>Denmark</span>'
		+'			</a>'
		+'			<a href="/ko/area/monaco" class="area_n_link">'
		+'				모나코&nbsp;<span>Monaco</span>'
		+'			</a>'
		+'			<a href="/ko/area/belgium" class="area_n_link">'
		+'				벨기에&nbsp;<span>Belgium</span>'
		+'			</a>'
		+'			<a href="/ko/area/romania" class="area_n_link">'
		+'				루마니아&nbsp;<span>Romania</span>'
		+'			</a>'
		+'			<a href="/ko/area/bulgaria" class="area_n_link">'
		+'				불가리아&nbsp;<span>Bulgaria</span>'
		+'			</a>'
		+'			<a href="/ko/area/sweden" class="area_n_link">'
		+'				스웨덴&nbsp;<span>Sweden</span>'
		+'			</a>'
		+'			<a href="/ko/area/switzerland" class="area_n_link">'
		+'				스위스&nbsp;<span>Switzerland</span>'
		+'			</a>'
		+'			<a href="/ko/area/spain" class="area_n_link">'
		+'				스페인&nbsp;<span>Spain</span>'
		+'			</a>'
		+'			<a href="/ko/area/finland" class="area_n_link">'
		+'				핀란드&nbsp;<span>Finland</span>'
		+'			</a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'<div class="area_white">'
		+'	<div class="wrap">'
		+'		<div class="area_title">'
		+'			해외 인기 여행지		</div>'
		+'		<div class="po_city_tab">'
		+'			<div class="po_city_area on" data="all">'
		+'				추천			</div>'
		+'			<div class="po_line">&nbsp;</div>'
		+'			<div class="po_city_area" data="as">'
		+'				아시아			</div>'
		+'			<div class="po_line">&nbsp;</div>'
		+'			<div class="po_city_area" data="eu">'
		+'				유럽			</div>'
		+'			<div class="po_line">&nbsp;</div>	'
		+'		</div>'
		+'		<div class="clear"></div>'
		+'		<div class="po_city_box">'
		+'			<div class="area_title">여기는 추천 여행지가 들어갈 예정.</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	common_menu : ()=>{
		return '<div class="wrap">'
		+'	<div class="area_nav">'
		+'		<a href="/ko/area" class="nav_btn">여행지</a>'
		+'			&gt; '
		+'		<a href="/ko/area/taiwan" class="nav_btn cu">대만</a>'
		+'	</div>'
		+'	<div class="area_title">'
		+'		<b>대만</b>'
		+'		<span>Taiwan</span>'
		+'	</div>'
		+'	<div class="common_menu">'
		+'		<div class="clear"></div>'
		+'	</div>'
		+'	<div class="inner_box">'
		+'		<div class="img_box"></div>'
		+'		<div class="img_right">'
		+'			<div class="country_info_box">'
		+'				<div class="country_info">'
		+'					<img src="http://img.earthtory.com/img/global_img/mobile/flag/taiwan.jpg" alt="" class="untry_flag">'
		+'					<div class="country_title">대만</div>'
		+'					<div class="clear"></div>'
		+'					<div class="country_desc">여기는 크롤링 할 곳이다.</div>'
		+'					<a href="http://ko.wikipedia.org/wiki/대만" target="_blank" class="info_more">더보기</a>'
		+'				</div>'
		+'				<div class="country_inner_box">'
		+'					<div class="country_info_box_title">환율계산</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="1">'
		+'							<b>대만</b><br>'
		+'							<span>TWD</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="1" value="100">'
		+'					</div>'
		+'					<div class="exchange_center">=</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="2">'
		+'							<b>대한민국</b><br><span>KRW</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="2" value="100">'
		+'					</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'	<div class="area_bg line white">'
		+'		<div class="wrap">'
		+'			<div class="area_title">'
		+'				인기도시'
		+'			</div>'
		+'			<div class="city_list">'
		+'			</div>	'
		+'		</div>'
		+'	</div>'
		+'</div>';
	}
}
