var compo = compo || {}
compo = {
	main_navi : ()=>{
		return '<div id="header">'
		+'	<div class="wrap">'
		+'			<h1 class="logo fl">'
						+'<a><img id="logo" alt="여행의 시작! 어스토리" ></a>'
		+'			</h1>'
		+'			<ul class="gnb fl">'
		+'				<a href="/ko/area" class="fl"><li class="on">여행지</li></a>'
		+'				<a href="/ko/plan" class="fl"><li>일정만들기</li></a>'
						+'<a href="https://www.agoda.com/?cid=1607809" class="fl" target="_blank"><li>호텔</li></a>'
		+'				<a href="/ko/intro" class="fl"><li>이용방법</li></a>'
		+'			</ul>'
		+'		<div class="fr gnb_box">'
						+"<a href='javascript:void(0)' class='fr' onclick='et_modal('365px','499px','1','0','/ko/member/join','2','1')'><div class='fl gnb_join_btn'>회원가입</div></a>"
						+"<a href='javascript:void(0)' class='fr' onclick='et_modal('365px','380px','1','0'','/ko/member','2','1')'><div class='fl gnb_login_btn'>로그인</div></a>"
		+'				<a href="javascript:void(0);" class="fr" style="display:none;">'
					+'<div class="fl gnb_set_box_currency script-popup" data-scp_child="gnb_set_box_open_currency" data-scp_ani="fade">'
		+'				<div style="padding-left:15px;">KRW</div>'
		+'			</div>'
					+'<div class="fl gnb_set_box_lang script-popup" data-scp_child="gnb_set_box_open_lang" data-scp_ani="fade">'
		+'				<div style="width:81px;padding-left:12px;">한국어</div>'
		+'			</div>			'
		+'					</a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'	<div class="clear"></div>'
		+'	<div id="common_area"></div>'
	},
	tourist_area : ()=>{
		return '<div class="area_top" id="area_top">'
		+'<div class="wrap">'
		+'	<div class="area_top_title">어디로 여행을 가시나요?</div>'
		+'		<div class="search_area">'
		+'			<input class="search_input" id="city_search" placeholder="국가명, 도시명으로 검색">'
		+'			<div id="city_autocomplete"></div>'
		+'			<div class="latest_search">	추천도시 :<a href="/ko/city/singapore_243" class="latest_a">싱가포르</a>'
		+'				,<a href="/ko/city/paris_307" class="latest_a">파리</a>'
		+'				,<a href="/ko/city/jeju_312" class="latest_a">제주도</a>'
		+'		</div>'
		+'			<a class="go_map" href="javascript:void(0)" onclick="et_full_modal("/ko/modal/world_map")">지도에서 검색 ></a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'<div class="area_white">'
		+'	<div class="wrap">'
		+'		<div class="area_title">'
		+'			국가리스트		</div>'
		+'		<div class="area_top_name as">'
		+'			아시아		</div>'
		+'		<div class="area_list as">'
		+'			<a href="/ko/area/nepal" class="area_n_link">'
		+'				마카오&nbsp;<span>Macau</span>'
		+'			</a>'
		+'			<a href="/ko/area/taiwan" class="area_n_link">'
		+'				인도네시아&nbsp;<span>Indonesia</span>'
		+'			</a>'
		+'			<a href="/ko/area/republic-of-korea" class="area_n_link">'
		+'				몰디브&nbsp;<span>Maldives</span>'
		+'			</a>'
		+'			<a href="/ko/area/laos" class="area_n_link">'
		+'				라오스&nbsp;<span>Laos</span>'
		+'			</a>'
		+'			<a href="/ko/area/vietnam" class="area_n_link">'
		+'				베트남&nbsp;<span>Vietnam</span>'
		+'			</a>'
		+'			<a href="/ko/area/sri-lanka" class="area_n_link">'
		+'				스리랑카&nbsp;<span>Sri Lanka</span>'
		+'			</a>'
		+'			<a href="/ko/area/singapore" class="area_n_link">'
		+'				싱가포르&nbsp;<span>Singapore</span>'
		+'			</a>'
		+'			<a href="/ko/area/myanmar" class="area_n_link">'
		+'				미얀마(버마)&nbsp;<span>Myanmar</span>'
		+'			</a>'
		+'			<a href="/ko/area/india" class="area_n_link">'
		+'				인도&nbsp;<span>India</span>'
		+'			</a>'
		+'			<a href="/ko/area/thailand" class="area_n_link">'
		+'				태국&nbsp;<span>Thailand</span>'
		+'			</a>'
		+'			<a href="/ko/area/japan" class="area_n_link">'
		+'				일본&nbsp;<span>Japan</span>'
		+'			</a>'
		+'			<a href="/ko/area/china" class="area_n_link">'
		+'				중국&nbsp;<span>China</span>'
		+'			</a>'
		+'			<a href="/ko/area/philippines" class="area_n_link">'
		+'				필리핀&nbsp;<span>Philippines</span>'
		+'			</a>'
		+'			<a href="/ko/area/hongkong" class="area_n_link">'
		+'				홍콩&nbsp;<span>Hongkong</span>'
		+'			</a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="area_top_name eu">'
		+'			유럽		</div>'
		+'		<div class="area_list eu">'
		+'			<a class="area_n_link" id="germany">'
		+'				독일&nbsp;<span>Germany</span>'
		+'			</a>'
		+'			<a href="/ko/area/united-kingdom" class="area_n_link">'
		+'				영국&nbsp;<span>United Kingdom</span>'
		+'			</a>'
		+'			<a href="/ko/area/russia" class="area_n_link">'
		+'				러시아&nbsp;<span>Russia</span>'
		+'			</a>'
		+'			<a href="/ko/area/poland" class="area_n_link">'
		+'				폴란드&nbsp;<span>Poland</span>'
		+'			</a>'
		+'			<a href="/ko/area/denmark" class="area_n_link">'
		+'				덴마크&nbsp;<span>Denmark</span>'
		+'			</a>'
		+'			<a href="/ko/area/monaco" class="area_n_link">'
		+'				모나코&nbsp;<span>Monaco</span>'
		+'			</a>'
		+'			<a href="/ko/area/belgium" class="area_n_link">'
		+'				벨기에&nbsp;<span>Belgium</span>'
		+'			</a>'
		+'			<a href="/ko/area/romania" class="area_n_link">'
		+'				루마니아&nbsp;<span>Romania</span>'
		+'			</a>'
		+'			<a href="/ko/area/bulgaria" class="area_n_link">'
		+'				불가리아&nbsp;<span>Bulgaria</span>'
		+'			</a>'
		+'			<a href="/ko/area/sweden" class="area_n_link">'
		+'				스웨덴&nbsp;<span>Sweden</span>'
		+'			</a>'
		+'			<a href="/ko/area/switzerland" class="area_n_link">'
		+'				스위스&nbsp;<span>Switzerland</span>'
		+'			</a>'
		+'			<a href="/ko/area/spain" class="area_n_link">'
		+'				스페인&nbsp;<span>Spain</span>'
		+'			</a>'
		+'			<a href="/ko/area/finland" class="area_n_link">'
		+'				핀란드&nbsp;<span>Finland</span>'
		+'			</a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'<div class="area_white">'
		+'	<div class="wrap">'
		+'		<div class="area_title">'
		+'			해외 인기 여행지		</div>'
		+'		<div class="po_city_tab">'
		+'			<div class="po_city_area on" data="all">'
		+'				추천			</div>'
		+'			<div class="po_line">&nbsp;</div>'
		+'			<div class="po_city_area" data="as">'
		+'				아시아			</div>'
		+'			<div class="po_line">&nbsp;</div>'
		+'			<div class="po_city_area" data="eu">'
		+'				유럽			</div>'
		+'			<div class="po_line">&nbsp;</div>	'
		+'		</div>'
		+'		<div class="clear"></div>'
		+'		<div class="po_city_box">'
		+'			<div class="area_title">여기는 추천 여행지가 들어갈 예정.</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	common_menu : ()=>{
		return 
		'<div class="area_bg top silver">' 
		+'<div class="wrap">'
		+'	<div class="area_nav">'
		+'		<a href="/ko/area" class="nav_btn">여행지</a>'
		+'			&gt; '
		+'		<a href="/ko/area/taiwan" class="nav_btn cu">대만</a>'
		+'	</div>'
		+'	<div class="area_title">'
		+'		<b>대만</b>'
		+'		<span>Taiwan</span>'
		+'	</div>'
		+'	<div class="common_menu">'
		+'		<div class="clear"></div>'
		+'	</div>'
		+'	<div class="inner_box">'
		+'		<div class="img_box"></div>'
		+'		<div class="img_right">'
		+'			<div class="country_info_box">'
		+'				<div class="country_info">'
		+'					<img src="http://img.earthtory.com/img/global_img/mobile/flag/taiwan.jpg" alt="" class="untry_flag">'
		+'					<div class="country_title">대만</div>'
		+'					<div class="clear"></div>'
		+'					<div class="country_desc">여기는 크롤링 할 곳이다.</div>'
		+'					<a href="http://ko.wikipedia.org/wiki/대만" target="_blank" class="info_more">더보기</a>'
		+'				</div>'
		+'				<div class="country_inner_box">'
		+'					<div class="country_info_box_title">환율계산</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="1">'
		+'							<b>대만</b><br>'
		+'							<span>TWD</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="1" value="100">'
		+'					</div>'
		+'					<div class="exchange_center">=</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="2">'
		+'							<b>대한민국</b><br><span>KRW</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="2" value="100">'
		+'					</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'	<div class="area_bg line white">'
		+'		<div class="wrap">'
		+'			<div class="area_title">'
		+'				인기도시'
		+'			</div>'
		+'			<div class="city_list">'
		+'			</div>	'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'</div>';
	},
	tourist_city : ()=>{
		return '<div class="wrap">'
		+'	<div class="attraction_menu">'
		+'		<div class="attraction_cate on" data-id="">'
		+'			전체			</div>'
		+'		<div class="attraction_cate " data-id="301">'
		+'			관광지			</div>'
		+'		<div class="attraction_cate " data-id="302">'
		+'			레저/액티비티			</div>'
		+'		<div class="attraction_cate " data-id="303">'
		+'			나이트라이프			</div>'
		+'		<div class="attraction_cate last" data-id="tip">'
		+'			여행TIP			</div>'
		+'		<div class="clear"></div>'
		+'	</div>'
		+'	<div class="category_list">'
		+'		<div class="category_box first">'
		+'			<div class="category_btn" data-id="301012" data-on="off">건축물</div>'
		+'			<div class="category_btn" data-id="301011" data-on="off">공원/정원/광장</div>'
		+'			<div class="category_btn" data-id="301010" data-on="off">관공서/학교</div>'
		+'			<div class="category_btn" data-id="301009" data-on="off">교통</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box ">'
		+'			<div class="category_btn" data-id="301008" data-on="off">기념관/기념비</div>'
		+'			<div class="category_btn" data-id="303001" data-on="off">나이트스팟</div>'
		+'			<div class="category_btn" data-id="302007" data-on="off">데이투어/액티비티</div>'
		+'			<div class="category_btn" data-id="301007" data-on="off">랜드마크</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box hide">'
		+'			<div class="category_btn" data-id="303002" data-on="off">바</div>'
		+'			<div class="category_btn" data-id="301006" data-on="off">박물관/미술관</div>'
		+'			<div class="category_btn" data-id="302001" data-on="off">스포츠</div>'
		+'			<div class="category_btn" data-id="301005" data-on="off">역사/종교</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box hide">'
		+'			<div class="category_btn" data-id="302006" data-on="off">오락/이벤트</div>'
		+'			<div class="category_btn" data-id="302005" data-on="off">웰니스/스파</div>'
		+'			<div class="category_btn" data-id="301004" data-on="off">유명거리/이색장소</div>'
		+'			<div class="category_btn" data-id="301002" data-on="off">자연</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box hide">'
		+'			<div class="category_btn" data-id="301001" data-on="off">전경/전망대</div>'
		+'			<div class="category_btn" data-id="302004" data-on="off">전시/공연/관람</div>'
		+'			<div class="category_btn" data-id="303003" data-on="off">클럽</div>'
		+'			<div class="category_btn" data-id="302003" data-on="off">테마파크/동물원</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box hide">'
		+'			<div class="category_btn" data-id="302002" data-on="off">트레킹/하이킹</div>'
		+'			<div class="category_btn" data-id="303004" data-on="off">펍/선술집</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_more" data-on="off">'
		+'			<span>카테고리 더보기</span>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	tourist_list : ()=>{
		return '<div class="wrap">'
		+'		<div class="list_top">'
		+'			<div class="list_cnt">'
		+'				총 <span>10</span>개		'
		+'			</div>'
		+'			<div class="list_sort">'
		+'				<select name="" id="" class="sort" data-height="25">'
		+'					<option value="pl_clip_cnt">인기순</option>'
		+'					<option value="pl_name">이름순</option>'
		+'				</select>'
		+'			</div>'
		+'		</div>'
		+''
		+'		<div id="paging">'
		+'			<span class="nv"></span>'
		+'			<button type="button" class="on">1</button>'
		+'			<button type="button">2</button>'
		+'			<button type="button">3</button>'
		+'			<button type="button">4</button>'
		+'			<button type="button">5</button>'
		+'			<button type="button">6</button>'
		+'			<button type="button">7</button>'
		+'			<button type="button">8</button>'
		+'			<button type="button">9</button>'
		+'			<button type="button">10</button>'
		+'			<span class="nv">'
		+'				<button type="button" class="pgn-nx2">다음</button>'
		+'				<button type="button" class="pgn-nx1">맨뒤로</button>'
		+'			</span>'
		+'		</div>'
		+'	<div class="clear"></div>'
		+'</div>';
	},
	tourist_main_city : ()=>{
		return '<div class="wrap">'
		+'	<div class="list_left">'
		+'		<div class="list_top">'
		+'			<div class="list_cnt">'
		+'				총 <span>9</span>개'
		+'			</div>'
		+'			<div class="list_sort">'
		+'				<select name="" id="" class="sort" data-height="25">'
		+'					<option value="cnt">인기순</option>'
		+'					<option value="ci_name">이름순</option>'
		+'				</select>'
		+'			</div>'
		+'		</div>'
		+'		<div class="list">'
		+'			<a class="box" id="taipai">'
		+'				<img src="http://img.earthtory.com/img/city_images/92/taipei_1425530262.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">타이베이</div>'
		+'					<div class="city_name_en">Taipei</div>'
		+'					<div class="spot_names">토은 전시관,타이베이 기차역,북문,국립중정기념당,국가도서관,국부사적기념관,총통부,우정박물관,타이베이...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'									<span>683</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>126</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>142</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>56</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/tainan_10403" class="box">'
		+'				<img src="http://mw2.google.com/mw-panoramio/photos/medium/44455874.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">타이난</div>'
		+'					<div class="city_name_en">Tainan</div>'
		+'					<div class="spot_names">雙全紅茶,林百貨 Hayashi Department Store,國立台灣文學館 National Museum of Taiwan Literature,臺南都...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'									<span>222</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>52</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'								<div class="city_cnt food">'
		+'									<div class="city_icon">'
		+'										<img src="/res/img/area/citys/food.png" alt="">'
		+'									</div>'
		+'									<span>128</span>'
		+'								</div>'
		+'								<div class="cnt_line"></div>'
		+'								<div class="city_cnt shopping">'
		+'									<div class="city_icon">'
		+'										<img src="/res/img/area/citys/shopping.png" alt="">'
		+'									</div>'
		+'									<span>34</span>'
		+'								</div>'
		+'								<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/yilan_10400" class="box">'
		+'				<img src="http://mw2.google.com/mw-panoramio/photos/medium/21428780.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">이란</div>'
		+'					<div class="city_name_en">Yilan</div>'
		+'					<div class="spot_names">北門綠豆沙牛奶,賣捌所藝文空間,紅樓中餐廳 Lantern Chinese Cuisine,Live食尚藝廊,渡小月,正常鮮肉小龍包...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'								<span>332</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>11</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>33</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>8</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/taitung_10404" class="box">'
		+'				<img src="http://mw2.google.com/mw-panoramio/photos/medium/19492276.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">타이둥</div>'
		+'					<div class="city_name_en">Taitung</div>'
		+'					<div class="spot_names">誠品台東書店 Eslite Bookstore,台東森林公園 Taitung Forest Park,鐵花村 Tie Hua Music Village,林家臭豆...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'								<span>183</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>14</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>20</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>5</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/kaohsiung_91" class="box">'
		+'				<img src="http://img.earthtory.com/img/city_images/91/kaohsiung_1425362067.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">가오슝</div>'
		+'					<div class="city_name_en">Kaohsiung</div>'
		+'					<div class="spot_names">가오슝원경관,삼봉궁,보얼예술특구,가오슝시립역사박물관,가오슝시전영도서관,애하,진애마두,가오슝85대루...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'								<span>271</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>26</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>8</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>4</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/pingtung_10402" class="box">'
		+'				<img src="http://mw2.google.com/mw-panoramio/photos/medium/24343259.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">핑둥</div>'
		+'					<div class="city_name_en">Pingtung</div>'
		+'					<div class="spot_names">Eske Place Coffee House,屏東夜市,Donutes 多那之咖啡蛋糕烘焙,太平洋百貨 屏東店,家樂福 屏東店,環球購物...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'								<span>20</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>18</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>9</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>6</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/hualien_10397" class="box">'
		+'				<img src="http://mw2.google.com/mw-panoramio/photos/medium/52508599.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">화롄</div>'
		+'					<div class="city_name_en">Hualien</div>'
		+'					<div class="spot_names">火車頭烤肉屋 Salt Lick,公正街包子店,阿之寶手創館 A Zhi Bao,中一豆花,花中榕樹下臭豆腐,松園別館 Pine G...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'								<span>533</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>9</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>13</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>3</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'			<a href="/ko/city/taichung_93" class="box">'
		+'				<img src="http://img.earthtory.com/img/city_images/93/taichung_1425529614.jpg" onerror="this.src="/res/img/common/mobile/no_img1.jpg";" alt="" class="main_city_img">'
		+'				<div class="city_right">'
		+'					<div class="city_name">타이중</div>'
		+'					<div class="city_name_en">Taichung</div>'
		+'					<div class="spot_names">보각사,타이중공원,타이중시정부,타이중 기차역,국립자연박물관,국립타이완미술관,타이중민속공원,동해대학...</div>'
		+'					<div class="city_cnt_box">'
		+'						<div class="city_cnt_inner">'
		+'							<div class="city_cnt hotel">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/hotel.png" alt="">'
		+'								</div>'
		+'								<span>197</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt sight">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/sight.png" alt="">'
		+'								</div>'
		+'								<span>14</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt food">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/food.png" alt="">'
		+'								</div>'
		+'								<span>4</span>'
		+'							</div>'
		+'							<div class="cnt_line"></div>'
		+'							<div class="city_cnt shopping">'
		+'								<div class="city_icon">'
		+'									<img src="/res/img/area/citys/shopping.png" alt="">'
		+'								</div>'
		+'								<span>4</span>'
		+'							</div>'
		+'							<div class="clear"></div>'
		+'						</div>'
		+'					</div>'
		+'				</div>'
		+'				<div class="clear"></div>'
		+'			</a>'
		+'		</div>'
		+'		<div id="paging">'
		+'			<span class="nv"></span>'
		+'			<button type="button" class="on" onclick="get_ci_list(26,1)">1</button>'
		+'			<button type="button" onclick="get_ci_list(26,2)">2</button>'
		+'			<span class="nv">'
		+'				<button type="button" class="pgn-nx1" onclick="get_ci_list(26,2)">맨뒤로</button>'
		+'			</span>'
		+'		</div>'
		+'	</div>'
		+'	<div class="list_right">'
		+'		<div class="right_box">'
		+'			<div class="right_title">'
		+'				지도에서 장소보기	'
		+'			</div>'
		+'			<div class="map_box">'
		+'				<img src="/res/img/city/map_view_btn.png" alt="" class="map_full" onclick="javascript:cu_map();">'
		+'			</div>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	city_detail : ()=>{
		return '<div class="wrap">'
		+'	<div class="inner_box">'
		+'		<div class="img_box"></div>'
		+'		<div class="img_right">'
		+'			<div class="country_info_box">'
		+'				<div class="country_info">'
		+'					<div class="country_title">날씨 들어가는 자리</div>'
		+'					<div class="clear"></div>'
		+'					<div class="country_desc">여기는 크롤링 할 곳이다.</div>'
		+'					<a href="http://ko.wikipedia.org/wiki/대만" target="_blank" class="info_more">더보기</a>'
		+'				</div>'
		+'				<div class="country_inner_box">'
		+'					<div class="country_info_box_title">환율계산</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="1">'
		+'							<b>대만</b><br>'
		+'							<span>TWD</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="1" value="100">'
		+'					</div>'
		+'					<div class="exchange_center">=</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="2">'
		+'							<b>대한민국</b><br><span>KRW</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="2" value="100">'
		+'					</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	restaurant_city : ()=>{
		return '<div class="wrap">'
		+'	<div class="category_list">'
		+'		<div class="attraction_menu">'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box first">'
		+'			<div class="category_btn" data-id="301012" data-on="off">현지요리</div>'
		+'			<div class="category_btn" data-id="301011" data-on="off">카페/디저트/베이커리</div>'
		+'			<div class="category_btn" data-id="301010" data-on="off">닭/오리요리</div>'
		+'			<div class="category_btn" data-id="301009" data-on="off">딤섬</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box ">'
		+'			<div class="category_btn" data-id="301008" data-on="off">면요리</div>'
		+'			<div class="category_btn" data-id="303001" data-on="off">북미요리</div>'
		+'			<div class="category_btn" data-id="302007" data-on="off">뷔페</div>'
		+'			<div class="category_btn" data-id="301007" data-on="off">스테이크/바비큐</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_more" data-on="off">'
		+'			<span>카테고리 더보기</span>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	shopping_city : ()=>{
		return '<div class="wrap">'
		+'	<div class="category_list">'
		+'		<div class="attraction_menu">'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box first">'
		+'			<div class="category_btn" data-id="301012" data-on="off">마트/식료품</div>'
		+'			<div class="category_btn" data-id="301011" data-on="off">면세점/아울렛</div>'
		+'			<div class="category_btn" data-id="301010" data-on="off">생활용품/기념품</div>'
		+'			<div class="category_btn" data-id="301009" data-on="off">쇼핑몰/백화점</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box ">'
		+'			<div class="category_btn" data-id="301008" data-on="off">시장/쇼핑거리</div>'
		+'			<div class="category_btn" data-id="303001" data-on="off">전문상점</div>'
		+'			<div class="category_btn" data-id="302007" data-on="off">화장품</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	}
}
